os:
  - linux
sudo: false

language: dart
dart:
  - dev

addons:
  apt:
    # sky_shell binary depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      # if we don't specify this, the libstdc++6 we get is the wrong version
      - ubuntu-toolchain-r-test
    packages:
      - lib32stdc++6
      - libstdc++6
      - fonts-droid
      - oracle-java8-set-default
cache:
  bundler: true
  directories:
    - $HOME/.pub-cache

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - hotfixes
    - /^hotfix\/.*$/
    - feat/travis
    - feat/tests

before_install:
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH=`pwd`/flutter/bin:$PATH
  - flutter doctor
  - bundle update
  - fastlane --version
install:
  - flutter packages get

script:
  - flutter test --name='unit test'
  - flutter build apk --release

after_success: |
  DEPLOY=false
  DEPLOY_PROD=false
  DEPLOY_DEV=false

  if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    DEPLOY_PROD=true
  elif [[ $TRAVIS_BRANCH =~ ^release/.*$ ]]; then
    DEPLOY_DEV=true
  elif [[ $TRAVIS_BRANCH =~ ^hotifx/.*$ ]]; then
    DEPLOY_DEV=true
  elif [[ $TRAVIS_BRANCH =~ ^release-.*$ ]]; then
    DEPLOY_DEV=true
  elif [[ $TRAVIS_BRANCH =~ ^hotifx-.*$ ]]; then
    DEPLOY_DEV=true
  fi

  if [[ "$DEPLOY_PROD" = true ]]; then
    DEPLOY=true
    FASTLANE_TRACK=production
  if [[ "$DEPLOY_DEV" = true ]]; then
    DEPLOY=true
    FASTLANE_TRACK=beta
  fi

before_deploy:
  - echo "DEPLOY = $DEPLOY"
  - echo "DEPLOY_PROD = $DEPLOY_PROD"
  - echo "DEPLOY_DEV = $DEPLOY_DEV"
  - echo "FASTLANE_TRACK = $FASTLANE_TRACK"

deploy:
  - provider: script
    script: bundle exec fastlane deploy_play_store
    skip_cleanup: true
    on:
      all_branches: true
      condition: $DEPLOY == true
